# Generated by Django 3.0.6 on 2020-05-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='images/')),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.CharField(max_length=250)),
                ('twitter', models.CharField(max_length=250)),
                ('youtube', models.CharField(max_length=250)),
            ],
        ),
    ]
