# Generated by Django 3.0.6 on 2020-05-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'company', 'verbose_name_plural': 'company'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date', 'title'], 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='publish',
            new_name='pub',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='publish_date',
            new_name='pub_date',
        ),
        migrations.AlterModelTable(
            name='company',
            table='company',
        ),
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='categorys',
            field=models.ManyToManyField(to='blog.Category'),
        ),
    ]
